version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
